project: default
test-name: example-name

services:
  microservice:
    image: af
    service_name: af
    ports:
      - "8009:8009"
      - "8010:8010"
    mem_limit: 512m
    cpus: 0.1

tests:
  default/http.gradual_ramp_up:
    path: "./tests/default/http.gradualRampUp.js"
    url: "https://test.com"
    request_type: "post"
    body: "{}"
    duration: 60
    total_requests: 25000
  
  default/http.spike_load:
    path: "./tests/default/http.spikeLoad.js"
    url: 
    request_type:
    body:
    duration:
    total_requests:

  default/http.sustained_high_load:
    path:
    url:
    request_type:
    body:
    duration:
    total_requests:
