version: "3.0"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: ares-infra-cadvisor
    hostname: ares-infra-cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - ares-telemetry
  
  prometheus:
    image: prom/prometheus
    container_name: ares-infra-prometheus
    hostname: ares-infra-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ares-prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - ares-telemetry

  grafana:
    image: grafana/grafana-enterprise
    container_name: ares-infra-grafana
    hostname: ares-infra-grafana
    volumes:
      - ares-grafana-storage:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - ares-telemetry

volumes:
  ares-prometheus-data:
  ares-grafana-storage:

networks:
  ares-telemetry:
    name: ares-telemetry