{
 "title": "default.network-device-api",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load Average for 10s ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{name=\"default.network-device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem - IO Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_io_current{name=\"default.network-device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"default.network-device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received/Transmitted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"default.network-device-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"default.network-device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}